### PR TITLE
Add copy to clipboard button

### PR DESCRIPTION
**Pull request by laurentpellegrino**
This is a quick patch for kcmr/code-sample#3.

The button style is customisable by using the new CSS mixin `--code-sample-copy-clipboard-button`.

### CODE REVIEW

**Comment by kcmr** [comment]
Thank you! I’ll try to take a look this weekend.

**Comment by kcmr** [comment]
Hi lpellegr,

After testing your PR I see two issues:

- The first one is that the button is not accessible for users not using a mouse or trackpad, because you have to :hover the code area to display the button. To solve this issue, I think that the best solution is to keep the button always visible so it can be focused using the keyboard. 
- The second is that the code is copied in one line. Line breaks are treated as spaces, so the pasted code requires manually edition.

Personally, I also would like the copy button to be optional using a boolean attribute to show it or not.

**Comment by laurentpellegrino** [comment]
@kcmr Thanks for your feedback. I have updated the PR to consider what you have said. Besides, I have added new CSS mixins required for advanced customizations.

**Comment by kcmr** [comment]
I'm going to do some minor changes:

- replace dom-if template by hidden (this way it's not necessary to import the dom-if template)
- clean indentation of the copied code

After adding some tests, it will be tagged as 0.4.0.
Thank you again!

**Pull request merged**
